# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Maven Build

on:
  push:
    branches: ["master" ]
  pull_request:
    branches: ["master"]
  workflow_dispatch:
  workflow_call:
  

jobs:
  maven-build:
    runs-on: ubuntu-20.04
    steps:
      - name: Git Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: 11
          distribution: temurin
          architecture: x64
          cache: maven
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.7
      - name: Search for bad unicode translations
        run: |
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F]' {} \; &> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[0-9a-fA-F][^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          find . -name \*.properties -exec grep '\\u[^0-9a-fA-F][0-9a-fA-F][0-9a-fA-F][0-9a-fA-F]' {} \; &>> grep.txt
          if [ -s grep.txt ]; then
            exit 1
          fi
      - name: Build with Maven
        env:
          MAVEN_OPTS: -Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=WARN -Dorg.slf4j.simpleLogger.showDateTime=true -Djava.awt.headless=true -Dmaven.wagon.http.retryHandler.count=2 -Dmaven.wagon.http.pool=true
        run: mvn --show-version --batch-mode -PskipBrokenTests test
  security-open-source:
    needs: maven-build
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
    - name: Run Snyk to check for vulnerabilities - Maven
      uses: snyk/actions/setup@master
    - run: snyk test --all-projects
      continue-on-error: false
      env:
        SNYK_TOKEN: ${{secrets.SNYK_API_TOKEN}}
